### ISSUE TITLE
Would it be possible to release a new version?

### ISSUE THREAD

**Issue by alexandrebouchard** [tbeason/NonparametricRegression.jl#8]
I am not able to install it at the moment because of the compat 0.8 on DocStringExtension clashing with Pigeons' 0.9 requirement. I see that the head of the repo already added 0.9 to its compat. Thank you!

**Comment by tbeason** [comment]
Done. #9 

I should note that I never finished fully developing this package, so it probably provides a rough user experience and YMMV. Happy to accept PRs.
